[theme]
primaryColor = "#FFFFFF"  # Change to a primary color for your theme
 # Set the main background color to white
secondaryBackgroundColor = "#F0F0F0"  # Light grey for secondary elements
textColor = "#000000"  # Text color to black for better readability
font = "sans serif"  # Choose your preferred font

[sidebar]
backgroundColor = "#FFFFFF"  # White background for the sidebar
textColor = "#000000"  # Text color for the sidebar
