[theme]
primaryColor = "##000000"  # Color of the primary elements (e.g., buttons)
secondaryBackgroundColor = "#F0F0F0"  # Light grey for secondary elements
textColor = "#000000"  # Text color for better readability
font = "sans serif"  # Font style for the app

[sidebar]
backgroundColor = "#FFFFFF"  # Sidebar background color
textColor = "#000000"  # Sidebar text color

[custom]
# Add any custom CSS styles here
